### ISSUE TITLE
Resource with Group By not able to Bulk export 

### ISSUE THREAD

**Issue by kevariable** [pxlrbt/filament-excel#100]
my query on the resource doesnt contains order by id but the export excel do something `order by id`

<img width="1315" alt="image" src="https://github.com/pxlrbt/filament-excel/assets/56016477/72a9821b-4b0c-47b8-9987-c1572345a2b5">

**Comment by pxlrbt** [comment]
I think every resource has a `ORDER BY` and if it's the default one.

**Comment by kevariable** [comment]
the table is fine, only after bulk export lead that error

**Comment by kevariable** [comment]
fixed, its error due `chunk()` method laravel, so in order we need orderBy itself

**Comment by pxlrbt** [comment]
Good to know. Thanks!
