### ISSUE TITLE
Grouping Exports in ExportBulkAction missing confirmation modal

### ISSUE THREAD

**Issue by akaflipper** [pxlrbt/filament-excel#103]
hi,
setup: 
Filament-excel: 2.0.1
Filament: 3.0.16
maatwebsite/excel: 3.1.48
Laravel: 10.18
Livewire: 3.0.0-beta7
PHP: 8.2.8

big fan ... in previous version used ( v1.1.13 ) grouping multiple exports presented modal to choose which export within ExportBulkAction with 
`ExportBulkAction::make('export')->exports([
                        ExcelExport::make('all')`

Update version for Filament v3 seems to ignore the multiple exports ... and just sends the first of the exports with ->exports([]) array . I tried BulkActions and HeaderActions .. Same result - straight to export.

```
ExportAction::make()->exports([
                ExcelExport::make('table')->fromTable(),
                ExcelExport::make('form')->fromForm(),
            ])
```

Docs say : 

You can overwrite the default export class and also configure multiple exports with different settings. The user will be shown a modal to select the export class he wants to use.

Can't seem to get new version to work like that. 
thanks 
g

**Comment by pxlrbt** [comment]
Thanks for bringing this up. I didn't think that the actions would require change for v3 and forgot to test this.
Hope I can have a look at it next week.
