### ISSUE TITLE
Custom column data in export

### ISSUE THREAD

**Issue by daar** [pxlrbt/filament-excel#105]
I have not found any reference on how to create a custom column that could contain a custom value e.g. "001" as Location. I tried using `modifyQueryUsing`, but got an error instead.

`->modifyQueryUsing(fn($query) => $query->addSelect(DB::raw('"001" as location')))`

gives

**Call to a member function getTable() on null**

**Comment by pxlrbt** [comment]
Hard to debug without any stacktrace and reproduction repo. Please at least share your Flare URL.

**Comment by pxlrbt** [comment]
Close as inactive
