### ISSUE TITLE
Exporting Excel of large amount of data

### ISSUE THREAD

**Issue by Umar-Farooq-Shafi** [pxlrbt/filament-excel#111]
Hey, I've data about 40K when I try to export the file. The browser got stuck and didn't respond even when I tried to export using `->queue()` and `->withChunkSize()` and set the size from 100 to 20K but it didn't work.

```
ExportBulkAction::make()->exports([
   ExcelExport::make('table')
          ->queue()
          ->withChunkSize(20000)
           ->fromTable(),
])
```

**Comment by pxlrbt** [comment]
You shouldn't use a BulkAction with that many records, because the BulkAction needs to send all 40k ids of your records to the backend which is what's probably causing the browser to crash/get stuck.

Best to use a Table Header Action in this case.

**Comment by Umar-Farooq-Shafi** [comment]
@pxlrbt Thanks, it's working.

**Comment by Umar-Farooq-Shafi** [comment]
What is the best size `withChunkSize`?

**Comment by pxlrbt** [comment]
> What is the best size `withChunkSize`?

I don't really now. I'd say something around 1000?

**Comment by Umar-Farooq-Shafi** [comment]
@pxlrbt The issue with the Table Header Action is that I have to filter out the record based on the date range but it's not applying on the Export. it's downloading all the records.

<img width="1025" alt="Screen Shot 2023-09-01 at 1 15 37 PM" src="https://github.com/pxlrbt/filament-excel/assets/62417503/98f90a40-368d-47de-87a9-1029df325765">

**Comment by pxlrbt** [comment]
You could use `->modifyQuery(fn ($livewire) -> )` to apply your filters. Haven't implemented that one yet apparently. But somebody else reported an issue with Depedency Injection into Closures. So for now there might be no solution to this

**Comment by Umar-Farooq-Shafi** [comment]
in the `getQuery` function I print out the `$this->getLivewire()`.
Is there any way to get `filters` from this?

<img width="1378" alt="Screen Shot 2023-09-01 at 1 58 10 PM" src="https://github.com/pxlrbt/filament-excel/assets/62417503/5690fecd-7925-4718-94c7-c60694b3f58a">

**Comment by pxlrbt** [comment]
`->tableFilters` should be what you are looking for. Depending on your version there should also be methods to get the table query.

**Comment by Umar-Farooq-Shafi** [comment]
`$this->getLivewire()->tableFilters` giving me null.

<img width="1378" alt="Screen Shot 2023-09-01 at 2 27 05 PM" src="https://github.com/pxlrbt/filament-excel/assets/62417503/0be58c03-9fb4-4dd6-ac5e-e26a5be52a7f">

**Comment by Umar-Farooq-Shafi** [comment]
I'm using Filament v3

**Comment by Umar-Farooq-Shafi** [comment]
Solve by using cache.
