### ISSUE TITLE
Bug: Enum could not be converted to string

### ISSUE THREAD

**Issue by ziming** [pxlrbt/filament-excel#12]
It would be nice if this package can auto call ->value if it detect the value is an Enum.

**Comment by ziming** [comment]
Hi, it looks like I can export now after a composer update, however if I try to export all records (3000 of them) a livewire white box appear and stays there forever.

**Comment by pxlrbt** [comment]
Does this only happen with larger datasets? Then you could try using `->queue()`.

**Comment by ziming** [comment]
Hi I try to do

                 ExportBulkAction::make('export')->queue()

But it seem like ->queue() method does not exist.

**Comment by pxlrbt** [comment]
Support for Enums has been shipped some time ago.
