### ISSUE TITLE
Bulk export with all columns

### ISSUE THREAD

**Issue by kossa** [pxlrbt/filament-excel#126]
Hello,

In my table I'm not showing all columns, when I select some rows in the bulk it does not export all column from form but from the table, here is my code:
```php
->bulkActions([
    ...,
    ExportBulkAction::make(),
]);
```

**Comment by pxlrbt** [comment]
Sorry, I don't understand your issue.

**Comment by kossa** [comment]
@pxlrbt In the table I'm showing 4 columns from DB, but in the form I have more then 10, when I make export it does not export all columns just the 4 columns in the table

**Comment by pxlrbt** [comment]
That's just the default. You can use `fromTable()` to use the table as a basis. Please read the readme.
