### ISSUE TITLE
When I enqueue a file to be exported, the file is empty

### ISSUE THREAD

**Issue by man0l** [pxlrbt/filament-excel#130]
Hi, 

I have this code:

` ->bulkActions([
                ExportBulkAction::make()->exports([
                    ExcelExport::make()->queue()
                ])
            ])
            ->headerActions([
                ExportAction::make()->exports([
                    ExcelExport::make()->queue()
                ])
            ])`
            
it doesn't seems to be working. On the other hand, when I use the default export it exports.

I've spotted that the both notifications for enqueued export file and for ready for download file are being popped up at the same time. It seems like it is missing some configuration.

Could you help me out to sesolve the issue?

**Comment by pxlrbt** [comment]
Hey @man0l, 
you didn't specify any columns that you want to export. You either need to pass them via `->withColumns()` or use `->fromTable()`/`->fromForm()`/`->fromModel()` to autodetect them.

**Comment by devfaysal** [comment]
Similar issue here

`ExportBulkAction::make()` works fine
But when I add file name its exporting empty excel sheet
```
ExportBulkAction::make()->exports([
    ExcelExport::make()->withFilename('zone-report-' . date('d-m-Y-H-i-s'))
])
```

**Comment by pxlrbt** [comment]
@devfaysal Did you read the previous message?!

**Comment by devfaysal** [comment]
Ah, Sorry, I Missed the earlier comment.

It works fine now after doing this
```
ExportBulkAction::make()->exports([
    ExcelExport::make()->withFilename('zone-report-' . date('d-m-Y-H-i-s'))->fromTable()
])
```
