### ISSUE TITLE
Table header action now extends Filament\Actions\Action

### ISSUE THREAD

**Issue by Michael-HEIW** [pxlrbt/filament-excel#132]
Following the documentation for Actions\Tables\ExportAction for table header actions, this now throws an exception in Filament v3

```php
use pxlrbt\FilamentExcel\Actions\Tables\ExportAction;

// ...

    protected function getHeaderActions(): array
    {
        return [
            ExportAction::make()->exports([
                ExcelExport::make('table')->fromTable(),
            ])
        ];
    }

// ....
```

This now throws an exception:

```text
InvalidArgumentException
PHP 8.2.9
10.29.0
Header actions must be an instance of Filament\Actions\Action, or Filament\Actions\ActionGroup.
```

The fix is to update **pxlrbt/filament-excel/src/Actions/Tables/ExportAction.php**

```diff
- use Filament\Tables\Actions\Action;
+ use Filament\Actions\Action; 
```

The export action then works as expected.

**Comment by buzkall** [comment]
The merged PR #133 breaks the code if you're adding a header option directly to the table function in the resource like this

```
->headerActions([
      ExportAction::make()->exports( [
              ExcelExport::make()->fromTable()
      ])
])
```
with version 2.1.7 throws exception "Method pxlrbt\FilamentExcel\Actions\Tables\ExportAction::table does not exist."
with version 2.1.6 works

**Comment by saulens22** [comment]
Yes, it seems to be broken.

`getHeaderActions()` is a method used for pages, so `pxlrbt\FilamentExcel\Actions\Pages\ExportAction` should be used.

`pxlrbt\FilamentExcel\Actions\Tables\ExportAction` should be only used like this:
```php
return $table
  ->columns([...])
  ->headerActions([
      \pxlrbt\FilamentExcel\Actions\Tables\ExportAction::make('myexportaction')->exports([
          // export logic
      ]),
  ]);
```

Pull request #133 should be reverted.

**Comment by pxlrbt** [comment]
Thanks for confirming. I just reverted the PR.

**Comment by pxlrbt** [comment]
@saulens22 Thanks for pointing out that the wrong Action was used.

**Comment by Michael-HEIW** [comment]
Sorry for the problem, that was not my intension. 

I tried the `return $table->headerAction` it worked perfect.
