### ISSUE TITLE
ExportAction On Header Action Error Or Bug

### ISSUE THREAD

**Issue by DeviJv** [pxlrbt/filament-excel#151]
Header actions must be an instance of Filament\Actions\Action, or Filament\Actions\ActionGroup.

i put into listrecord page resource and error like that 

thx dev

**Comment by kombiahrk** [comment]
**Make sure this two line is there in listrecord page of your resource**

use pxlrbt\FilamentExcel\Exports\ExcelExport;
use pxlrbt\FilamentExcel\Actions\Pages\ExportAction;

**Comment by pxlrbt** [comment]
@DeviJv No need to open another issue. I answered your first one already: #150

**Comment by DeviJv** [comment]
thx bro
