### ISSUE TITLE
enum() and counts() are not evaluated

### ISSUE THREAD

**Issue by kamilst96** [pxlrbt/filament-excel#16]
I am trying to move from 0.x, and encountered the following issues:
- When `enum([1 => 'Text'])`, exported field will contain `1`.
- In case of `counts('relationship')`, exported field will be blank.
- Sorting is not honored.

For the last one, could you expose a method allowing to mutate `Builder $query` before firing?

**Comment by pxlrbt** [comment]
This should be fixed by #23
