### ISSUE TITLE
[Feature request] Add support for toggleable columns

### ISSUE THREAD

**Issue by ralphjsmit** [pxlrbt/filament-excel#17]
I was reviewing options for exporting Excel-sheets from Filament. For a client it is very important to be able to select the columns that are visible (and which not), so I was wondering whether toggleable columns. That wasn't the case, but it would be a nice feature for sure!

**Comment by pxlrbt** [comment]
With the next version, this works with `->fromTable()` (#30)

**Comment by ralphjsmit** [comment]
O cool, nice!
