### ISSUE TITLE
[Bug] It crashes when trying to bulk export using Filament relation manager - relation page

### ISSUE THREAD

**Issue by ericmp33** [pxlrbt/filament-excel#186]
I have a Form model and a Response model. A form has many responses, and a response belongs to a form.

If i go to `/admin/forms/1/responses` and i try to bulk export, I get:
![image](https://github.com/pxlrbt/filament-excel/assets/60661635/811127b5-6c4a-4639-ab35-fba8e2aa5e74)

I have built a really simple setup so you can debug it:
https://github.com/ericmp33/example-app

Steps to reproduce the bug:
1. php artisan migrate:fresh --seed
2. go to `/admin/forms/1/responses`
3. bulk export

Filament docs on relation pages:
https://filamentphp.com/docs/3.x/panels/resources/relation-managers#relation-pages

**Comment by ericmp33** [comment]
@pxlrbt Hi!! I need to fix this. You plan to fix it? If not, please, I'd appreciate some guidance on how can I fix it myself 🥺 🙏

**Comment by pxlrbt** [comment]
@ericmp33 Sorry, I currently don't have the time to look into this. I think someone had the same issue with the `ManageRelatedRecords`. It was introduced with v3 and I haven't used it yet, so I couldn't adjust the implementation. 

Hard to tell where to look. I'd start with the `ExcelExport` class and check for the models etc. 

Sorry, that's no big help.
