### ISSUE TITLE
[Feature request] Add the ability to modify the query and add custom fields

### ISSUE THREAD

**Issue by bezhanSalleh** [pxlrbt/filament-excel#19]
Something like Action Modals does 

https://user-images.githubusercontent.com/10007504/177214175-12c258a5-f122-4672-a7b5-d7caa68808e5.mov

**Comment by pxlrbt** [comment]
You can now modify the query. #31

**Comment by Rahul-codoffer** [comment]
@bezhanSalleh Plz can you tell as how did you export the data with the custom input.

**Comment by pxlrbt** [comment]
@Rahul-codoffer You just need to overwrite `->form()` on the action. Here is the default source code for it: https://github.com/pxlrbt/filament-excel/blob/eaea34d4bd0f31553d0df9f70a3b010ae07b4c29/src/Actions/Concerns/ExportableAction.php#L26-L35

**Comment by Rahul-codoffer** [comment]
@pxlrbt  Thanks man !

**Comment by marwanemoufakkir** [comment]
I’m trying to use a custom input field in the export modal (e.g., rowLimit). What’s the correct way to access the custom input values (like rowLimit) inside modifyQueryUsing()?
