### ISSUE TITLE
Problem with download

### ISSUE THREAD

**Issue by papipsycho** [pxlrbt/filament-excel#193]
Hello, 

I have a strange issue when i click on the export button from the BulkActionGroup is not working (i mean is not downloading without any error), but if i click on the button created by ExportBulkAction is working, but i need to customize the columns

```
->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                    ExportAction::make()->exports([
                        ExcelExport::make()->withColumns([
                            Column::make('domain'),
                            Column::make('created_at'),
                        ]),
                    ])
                ]),
                ExportBulkAction::make()

            ]);
```

**Comment by pxlrbt** [comment]
You are mixing up `BulkExportAction` and `ExportAction`. Just use the `BulkExportAction`. You can customize the columns the same way.
