### ISSUE TITLE
ExportAction::make must be compatible with BaseAction::make

### ISSUE THREAD

**Issue by marcusmyers** [pxlrbt/filament-excel#20]
I've updated everything to the latest version in my laravel app and keep getting this error.

```
Declaration of pxlrbt\FilamentExcel\Actions\Pages\ExportAction::make(string $name = 'export'): static must be compatible with Filament\Support\Actions\BaseAction::make(?string $name = null): static
```

I'm just trying to add an action to my resource page. I've tried the `ExportBulkAction` as well to use with my table method on my resource page and get a `Class "pxlrbt\FilamentExcel\Actions\Pages\ExportBulkAction" not found`.

**Comment by pxlrbt** [comment]
Hey guys, I try to push a fix after the weekend.
