### ISSUE TITLE
how to export filament repeater json format ?

### ISSUE THREAD

**Issue by alvinChristianto** [pxlrbt/filament-excel#204]
I implement filament repeater form that will result json format in database. but when I implement export function the record only show the value not with the key. 
here is my code : 

![image](https://github.com/user-attachments/assets/ab855dc9-64be-47f7-9a7f-54d7636c9319)

and this is the data in database :
![image](https://github.com/user-attachments/assets/6cea17e1-0772-4e1d-a027-6d1b91cc9e1b)

the exported excel file : 
![image](https://github.com/user-attachments/assets/2f4c945d-6398-4239-a360-03367f9b2412)

what is the best way to export this kind of data ?

**Comment by pxlrbt** [comment]
Is it bad data or is it just Excel messing with the data because of the format?

**Comment by alvinChristianto** [comment]
I think its because of format

yeah i try to implememnt `formatStateUsing()`, but still confuse because the data can have array in it, while `formatStateusing()` doesnt handle foreach

**Comment by pxlrbt** [comment]
> while formatStateusing() doesnt handle foreach

Not sure what you mean. It should give you the whole data and you can format it to your liking.
But maybe you just need to set the Excel cell format to something else.

**Comment by alvinChristianto** [comment]
finally still cant done it correctly. 

I make another table like to handle data in TEXT format, then show it in json format : https://github.com/alvinChristianto/filaminiReservation/commit/eb5d8ac9f03b51923f0f47c7de7a7a738f21387e#diff-23fae0449c02de936db867d2985abcf00d3bbe4d43500d57b256077a8130b5a7
