### ISSUE TITLE
Better integration with existing code

### ISSUE THREAD

**Issue by mokhosh** [pxlrbt/filament-excel#22]
Hi
Thanks for the great package. I tried this in my newest project and I have a few suggestions.

It would be great if the exports:
1. used the same query as the resource page. Currently they're not using my custom query and they're unable to export the aggregated and calculated columns.
2. used the same formatStateUsing and getStateUsing closures without having to define the exact same thing twice. Currently these are the same function and they are not aware of the already available code.
4. respected current toggleable settings of the user.

Please let me know if these are on the roadmap, and if we can help make these happen.

**Comment by mokhosh** [comment]
Thanks, good to know you're open to accepting PRs.

Tackled the first one in https://github.com/pxlrbt/filament-excel/pull/23
Next ones to come.

**Comment by mokhosh** [comment]
Another thing we can do is add the eager loads and aggregates if they're defined on the column.

**Comment by pxlrbt** [comment]
Sure. Happy to accept a PR. Ideally it works with forms, too.

**Comment by mokhosh** [comment]
Would love to put the PR together but im not sure how they work in filament. Do we have any resource or should i just start reading a lot of code?
