### ISSUE TITLE
After queued export is finished, when do the download start?

### ISSUE THREAD

**Issue by ziming** [pxlrbt/filament-excel#24]
I did a queued export, then got a notification the export is finished but my browser did not start the download, how can it be started?

**Comment by pxlrbt** [comment]
By the time v1.0.0 was released, there was no way to show actions or HTML. Currently, it's possible to add HTML into notifications to show a link, but I will wait for filament/notifications package for dismissible notifications and actions.

**Comment by ziming** [comment]
Hi there, the filament notifications package is merged!

**Comment by mvanbeekum** [comment]
How can we add HTML into the notification? I can see you've got the logic in there that wraps the file in an anchor tag, but it's commented out.

**Comment by pxlrbt** [comment]
This will use the new notification package with the next update. Just didn't have the time for the other feature I want to implement.

**Comment by pxlrbt** [comment]
Closed via #28
