### ISSUE TITLE
composer error (Laravel 9)

### ISSUE THREAD

**Issue by saschagysel** [pxlrbt/filament-excel#3]
I get the following error when trying to install with composer in Laravel 9 with fully updated filament, livewire and Laravel.

`  Problem 1
    - phpoffice/phpspreadsheet[1.18.0, ..., 1.22.0] require psr/simple-cache ^1.0 -> found psr/simple-cache[1.0.0, 1.0.1] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - maatwebsite/excel[3.1.0, ..., 3.1.25] require php ^7.0 -> your php version (8.1.2) does not satisfy that requirement.
    - maatwebsite/excel[3.1.26, ..., 3.1.35] require illuminate/support 5.8.*|^6.0|^7.0|^8.0 -> found illuminate/support[v5.8.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - pxlrbt/filament-excel 0.1.2 requires maatwebsite/excel ^3.1 -> satisfiable by maatwebsite/excel[3.1.0, ..., 3.1.x-dev].
    - maatwebsite/excel[3.1.36, ..., 3.1.x-dev] require phpoffice/phpspreadsheet ^1.18 -> satisfiable by phpoffice/phpspreadsheet[1.18.0, ..., 1.22.0].
    - Root composer.json requires pxlrbt/filament-excel ^0.1.2 -> satisfiable by pxlrbt/filament-excel[0.1.2].`

**Comment by pxlrbt** [comment]
@saschagysel 

Sounds like your lockfile contains `psr/simple-cache:3.0.0` as Laravel 9 supports it.
But Laravel Excel requires `psr/simple-cache:^1.0.`. You should be able to solve this with: `composer require psr/simple-cache:^1.0`.

**Comment by pxlrbt** [comment]
Solved via Discord.
