### ISSUE TITLE
Error executing "SendMessage" on SQS queue driver

### ISSUE THREAD

**Issue by ziming** [pxlrbt/filament-excel#37]
I suppose this happen probably because it exceed the max size allowed for SQS

so I wonder if it is possible to specify another queue driver for this package in config (say maybe database queue driver) while the rest of my app use SQS

**Comment by pxlrbt** [comment]
I think the issue is, that for `->formatStateUsing()` etc. a lot of Closures are serialized.

Can you try overwriting `export()` on `ExcelExport` and defining a separate connection:

```php
        $this
            ->queueExport($filename, 'filament-excel', $this->getWriterType())
            ->onConnection('your_connection')
            ->chain([fn () => ExportFinishedEvent::dispatch($filename, $userId)]);
```

**Comment by pxlrbt** [comment]
Closing as stale.
