### ISSUE TITLE
Exporting via route?

### ISSUE THREAD

**Issue by Sanabria** [pxlrbt/filament-excel#46]
Would it be possible to export the file by accessing a route? Something like what Laravel Excel does: https://docs.laravel-excel.com/3.1/exports/#_5-minute-quick-start

I would like to initiate the export with a button placed in the dashboard, rather than from a headeraction/bulkaction.

Thanks in advance

**Comment by pxlrbt** [comment]
Not sure how this would work, as a lot of the logic is coupled to the Livewire components.

**Comment by bezhanSalleh** [comment]
@Sanabria in 4 steps i think:

1. Create a model with migration lets say `Reports` with `name`,`path` and `generated_by` columns(you can name them as you want).
2. create a listener for `ExportFinishedEvent`, this event has two parameters `$filename` and `userId`
 ```php
 public function handle(ExportFinishedEvent $event)
    {
        Report::create([
            'name' => substr($event->filename, 37),
            'path' => $event->filename,
            'generated_by' => User::find($event->userId)->name
        ]);
    }
```
3. Add this route:
```php
Route::get('download-report/{path}', function (string $path) {
    return response()->download(
        Storage::disk('filament-excel')
            ->path($path),
        substr($path, 37)
    );
})
->where('path', '.*')
->name('download-report');
```
4. Create a resource with only the index page. you don't need the rest.    
you can download the report either via column:
```php
Tables\Columns\TextColumn::make('name')
      ->url(fn ($record): string => route('download-report', ['path' => $record->path])),
```
or table action:
```php
          Tables\Actions\Action::make('download')
                    ->icon('heroicon-o-download')
                    ->color('warning')
                    ->button()
                    ->url(fn ($record): string => route('download-report', ['path' => $record->path]))
                    ->openUrlInNewTab()
``` 
<img width="1465" alt="Screenshot 2022-11-16 at 9 49 45 PM" src="https://user-images.githubusercontent.com/10007504/202249318-ad66a32d-c52d-445b-bf45-ce2a940b8642.png">


@pxlrbt you can close it now i think.

**Comment by pxlrbt** [comment]
Thanks @bezhanSalleh
