### ISSUE TITLE
Notifications can be displayed more than once

### ISSUE THREAD

**Issue by drzippie** [pxlrbt/filament-excel#51]
One Export can show the same notification more than once

![Screenshot 2022-12-17 at 11 51 00](https://user-images.githubusercontent.com/239421/208238165-ab4fb5f8-2d8a-4c91-9d48-91a6ce0d85d8.png)

Current image is from one queued export

Proposed change: https://github.com/pxlrbt/filament-excel/pull/52

**Comment by pxlrbt** [comment]
Weird. Never had that happening, but if it an be fixed that's good.
