### ISSUE TITLE
After download (and deleted file) the notification is showed 

### ISSUE THREAD

**Issue by drzippie** [pxlrbt/filament-excel#53]
The notification is showing again and link returns (example):

![Screenshot 2022-12-17 at 12 07 35](https://user-images.githubusercontent.com/239421/208238741-d86829a9-9746-4757-b0e3-bd96298cd3ba.png)

**Comment by drzippie** [comment]
updated PR (fix conflicts)

**Comment by pxlrbt** [comment]
PR #54 was merged.
