### ISSUE TITLE
Not support UUID or another string key type when use queued

### ISSUE THREAD

**Issue by topkstt** [pxlrbt/filament-excel#57]
![Screenshot 2565-12-30 at 02 50 48](https://user-images.githubusercontent.com/29277624/210005032-a073d8fb-d3e0-4aa8-9c71-13bd19ad27d8.png)

![Screenshot 2565-12-30 at 02 51 21](https://user-images.githubusercontent.com/29277624/210005080-fc5f23aa-5e89-404d-935a-fc70a81a8236.png)

The finished event allow to use only int as a user id.

**Comment by pxlrbt** [comment]
Thanks. I'll have a look at it with the next release.
