### ISSUE TITLE
Export fails with large dataset

### ISSUE THREAD

**Issue by s7thamon** [pxlrbt/filament-excel#61]
I have a slightly large table (2664412 records currently) that I'm filtering via date range. Unable to get an export going if the selection is greater than a few thousand records. Clicking export will just hang, then I notice in debug console that the response from the post request results in a 502 bad gateway. Unsure how to resolve this, assumed the queue and chunk option would have had an impact.

```
ExportBulkAction::make()->exports([
    ExcelExport::make()->fromModel()->withFilename(date('Y-m-d') . '_telemetry_export')->queue()->withChunkSize(500)
])
```

![image](https://user-images.githubusercontent.com/66268528/221223368-1f44a516-c405-4938-aa2b-2871d6aa365c.png)

**Comment by pxlrbt** [comment]
Queue and Chunk should have an impact on the export. But your issue is probably all the IDs that are sent to the server. Best to use a Table Header Action instead of a Bulk Action.

**Comment by s7thamon** [comment]
`2023/02/27 14:48:16 [error] 1024#1024: *52483 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 205524992 bytes) in /home/forge/api.test.com/vendor/laravel/horizon/src/JobPayload.php on line 196" while reading response header from upstream, client: 65.190.151.251, server: api.test.com, request: "POST /livewire/message/app.filament.resources.vehicle-resource.pages.list-vehicles HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "api.test.com", referrer: "https://api.test.com/admin/vehicles?tableSortColumn=created_at&tableSortDirection=desc&tableFilters[created_at][from]=2023-02-21+19%3A00%3A00&tableFilters[created_at][until]=2023-02-22+00%3A00%3A00"`

Looks like it's still hitting memory limits despite giving it 1GB of RAM

**Comment by pxlrbt** [comment]
Sounds like it tries to encode all your models into the payload. Have you tried with a small chunkSize?

**Comment by pxlrbt** [comment]
@s7thamon Did you figure this out?
