### ISSUE TITLE
In ExportBulkAction - remove limit() from the columns

### ISSUE THREAD

**Issue by lalov** [pxlrbt/filament-excel#62]
Hi
I have enabled ExportBulkAction::make() in the ->bulkActions() section of a Filament Resource. 
Would be very nice if the limit(20) clause on the columns in the table could be removed when exporting the data. 

For instance this column: 

         Tables\Columns\TextColumn::make('comment')
              ->translateLabel()
              ->limit(20),

During export, I would like to see the full content. 

Is this possible?

**Comment by pxlrbt** [comment]
Just overwrite the `formatStateUsing()` with something like this:
`Column::make('comment')->formatStateUsing(fn ($record) => $record->comment)`
