### ISSUE TITLE
Exporting a model's relation data

### ISSUE THREAD

**Issue by nikolaos-spyratos** [pxlrbt/filament-excel#63]
Hi there. Trying something perhaps unexpected with this package.

Contrary to #8 and #47, I'm looking to create an export of the relation on the original model (a HasMany/BelongsTo relation). For example, on an Author page, export all their Books. This is for admin UX purposes - far easier to go to the parent model and pull out its relations than query its relations and try to do an export of that from the table.

Is there a way to do that with this package? I've tried a few workarounds:
- Trying to override the query to use the relation doesn't work because of the `ExcelExport:getQuery` function which adds the `whereIn` for the parent model's primary key. 
- I've tried overriding that key in a custom export class, but that doesn't work either because `hydrate` will override it due to the `modelInstance`'s key. 
- Trying to set the `modelInstance` to the child relation and overriding the parent key with `setKeyName` doesn't work, because then `hydrate` fails to find the record ID of the parent model in the `recordIds` array, which turns the `whereIn` into `where key_name in (0)`.

**Comment by nikolaos-spyratos** [comment]
For now I've gone ahead with just using the Laravel Excel export manually, since Filament "just works" with returning `Excel()->download()` in the action logic. But this can still be considered a potential feature request.

**Comment by pxlrbt** [comment]
I guess using the underlying maatswebsite/laravel-excel package is the way to go here. This package is already quite complex as it tries to make use of all the existing Filament definitions. Adding some edge cases will make it harder to maintain this.
