### ISSUE TITLE
Table ExportAction trigger error on List page

### ISSUE THREAD

**Issue by raditzfarhan** [pxlrbt/filament-excel#64]
Hi, I'm trying to add the Export action next to the Create button on List page but unable to do so. Here is the snippet:-

```
use App\Exports\InspectionExport;
use pxlrbt\FilamentExcel\Actions\Tables\ExportAction;

class ListInspections extends ListRecords
{
    protected static string $resource = InspectionResource::class;

    protected function getActions(): array
    {       
        return [
            Actions\CreateAction::make(),
            ExportAction::make()->exports([
                 InspectionExport::make(),
            ]),
        ];
    }
```

It will prompt this error as below:-

![image](https://user-images.githubusercontent.com/1203676/228722127-5652918d-927d-43f7-96b0-c47a27930ef8.png)

I'm not sure if I use it correctly though. Let me know if it's not the way how it works. What I'm trying to achieve is something like below:-

![image](https://user-images.githubusercontent.com/1203676/228722487-9580259d-a957-45d9-9d71-f6feffd0d573.png)

Thanks for your time.

**Comment by pxlrbt** [comment]
I think the issue is, that you are trying to use a Table Action on a Page. You can use the Page Action and it should wokr.

**Comment by raditzfarhan** [comment]
Thanks for your reply. If I use Page Action, yes the button will appear. But I encounter a new error as shown below. Not sure what I'm missing.

![image](https://user-images.githubusercontent.com/1203676/229974822-d043b625-07d6-4782-960d-f837f76a1cf6.png)

**Comment by pxlrbt** [comment]
Mh, I think you can't define them on the ListPage currently, then. Can you try via Resource and the `->headerActions()` and remove `getActions()`?
