### ISSUE TITLE
LibreOffice WriterType ODS

### ISSUE THREAD

**Issue by mackhankins** [pxlrbt/filament-excel#69]
Are you opposed to adding support for .ods extension?  It's supported.

https://github.com/pxlrbt/filament-excel/blob/f37572c2011168d718c6050769bbdc248fa9fe9b/src/Interactions/AskForWriterType.php

**Comment by mackhankins** [comment]
Wow, I'm tired.  You can set this on the action method even with default.  Here is an example

```php
->askForWriterType(Excel::ODS,[
    Excel::XLS  => 'XLS',
    Excel::XLSX => 'XLSX',
    Excel::CSV  => 'CSV',
    Excel::ODS => 'ODS'
])
```

**Comment by mackhankins** [comment]
Wow, I'm tired.  You can set this on the action method even with default.  Here is an example

```php
->askForWriterType(Excel::ODS,[
    Excel::XLS  => 'XLS',
    Excel::XLSX => 'XLSX',
    Excel::CSV  => 'CSV',
    Excel::ODS => 'ODS'
])
```

**Comment by pxlrbt** [comment]
I think if it works this way, I'd like to keep the defaults to the current 3.
