### ISSUE TITLE
exporting data too large error

### ISSUE THREAD

**Issue by oz-hjx210** [pxlrbt/filament-excel#70]
I encounter an error when exporting data, and the export operation cannot be completed when the data is too large.

It is normal when there are 10,000 data records, but an error occurs when there are over 20,000 data records.

![image](https://user-images.githubusercontent.com/120376499/232808650-19a6582e-b7ac-42a8-80f6-9a7530b07034.png)

![image](https://user-images.githubusercontent.com/120376499/232808948-46718997-109a-4b1f-8b53-78c225b05645.png)

**Comment by mackhankins** [comment]
Are you sending this to queue?

**Comment by pxlrbt** [comment]
If you encounter issues with large exports you should try the queue options as mackhankins said.

**Comment by oz-hjx210** [comment]
where can i  sending this to queue?  i am sorry  ,can you  show me a demo  code,  thanks  very much!

**Comment by mackhankins** [comment]
https://laravel.com/docs/10.x/queues
https://github.com/pxlrbt/filament-excel#queued-exports

**Comment by oz-hjx210** [comment]
I used a queue, but still encountered errors. Whenever it exceeds 40 seconds, the error occurs.

**Comment by pxlrbt** [comment]
@oz-hjx210 can you share the plugin code you use and the queue settings from `.env`?

**Comment by oz-hjx210** [comment]
ExportAction::make('q')->exports([
                    ExcelExport::make()

                        ->withColumns([
                        Column::make('huokuang')->heading('貨況')->getStateUsing(fn ($state) => $huokuang[$state]),
                        Column::make('title')->heading('ITEMNO'),
                        Column::make('brand')->heading('BRAND'),
                        Column::make('dc')->heading('D/C'),
                        Column::make('package')->heading('PACKAGE'),
                        Column::make('kucunliang')->heading('庫存量'),
                        Column::make('jiaoqi')->heading('交期/備註'),
                        Column::make('changshang')->heading('廠商'),
                        Column::make('priceone.0.bibie')->heading('幣別'),
                        Column::make('priceone.0.jiage')->heading('價格'),
                        Column::make('priceone.0.baojiariqi')->heading('歷史報價日期'),
                        Column::make('dealresone.0.jiaoyiriqi')->heading('交易日期'),
                        Column::make('dealresone.0.guobie')->heading('國別'),
                        Column::make('dealresone.0.kehu')->heading('客戶'),
                        Column::make('dealresone.0.shuliang')->heading('數量'),
                        Column::make('dealresone.0.danjia')->heading('單價'),
                    ])
                    ->withFilename(date('YmdHis') . 'export')
                    ->withWriterType(\Maatwebsite\Excel\Excel::XLS)
                    ->queue()

**Comment by pxlrbt** [comment]
@oz-hjx210 What about the queue settings? What did you set `QUEUE_CONNECTION=` to?

**Comment by oz-hjx210** [comment]
I'm sorry, I haven't used Laravel Queue before and I don't know how to set it up. Can you help me with the instructions?

**Comment by oz-hjx210** [comment]
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Default Queue Connection Name
    |--------------------------------------------------------------------------
    |
    | Laravel's queue API supports an assortment of back-ends via a single
    | API, giving you convenient access to each back-end using the same
    | syntax for every one. Here you may define a default connection.
    |
    */

    'default' => env('QUEUE_CONNECTION', 'sync'),

    /*
    |--------------------------------------------------------------------------
    | Queue Connections
    |--------------------------------------------------------------------------
    |
    | Here you may configure the connection information for each server that
    | is used by your application. A default configuration has been added
    | for each back-end shipped with Laravel. You are free to add more.
    |
    | Drivers: "sync", "database", "beanstalkd", "sqs", "redis", "null"
    |
    */

    'connections' => [

        'sync' => [
            'driver' => 'sync',
        ],

        'database' => [
            'driver' => 'database',
            'table' => 'jobs',
            'queue' => 'default',
            'retry_after' => 90,
            'after_commit' => false,
        ],

        'beanstalkd' => [
            'driver' => 'beanstalkd',
            'host' => 'localhost',
            'queue' => 'default',
            'retry_after' => 90,
            'block_for' => 0,
            'after_commit' => false,
        ],

        'sqs' => [
            'driver' => 'sqs',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'prefix' => env('SQS_PREFIX', 'https://sqs.us-east-1.amazonaws.com/your-account-id'),
            'queue' => env('SQS_QUEUE', 'default'),
            'suffix' => env('SQS_SUFFIX'),
            'region' => env('AWS_DEFAULT_REGION', 'us-east-1'),
            'after_commit' => false,
        ],

        'redis' => [
            'driver' => 'redis',
            'connection' => 'default',
            'queue' => env('REDIS_QUEUE', 'default'),
            'retry_after' => 90,
            'block_for' => null,
            'after_commit' => false,
        ],

    ],

    /*
    |--------------------------------------------------------------------------
    | Failed Queue Jobs
    |--------------------------------------------------------------------------
    |
    | These options configure the behavior of failed queue job logging so you
    | can control which database and table are used to store the jobs that
    | have failed. You may change them to any database / table you wish.
    |
    */

    'failed' => [
        'driver' => env('QUEUE_FAILED_DRIVER', 'database-uuids'),
        'database' => env('DB_CONNECTION', 'mysql'),
        'table' => 'failed_jobs',
    ],

];

**Comment by oz-hjx210** [comment]
QUEUE_CONNECTION=sync

**Comment by pxlrbt** [comment]
The `sync` driver is not a real queue driver, as jobs will be processed immediately. Sorry, but Queues are a bit too complex to give some help via GitHub. Please check the Laravel docs.

**Comment by oz-hjx210** [comment]
I don't understand the specific usage logic. Assuming I have set up a JOB, should I call it in the ->queue() method?

**Comment by oz-hjx210** [comment]
I found that there is no problem exporting the data of 30,000 records for the main table only, but if I export 20,000 records, which include the data from the child table （realtion many）, an error will occur. It seems that if the processing time of the program logic exceeds 40 seconds, an error will be reported.

**Comment by pxlrbt** [comment]
> It seems that if the processing time of the program logic exceeds 40 seconds

Yeah, that's probably the request timeout of PHP which is set to 30s most of the time. You can either increase this or use a queue.

> I don't understand the specific usage logic. Assuming I have set up a JOB, should I call it in the ->queue() method?

All you need is a queue (like DB or Redis) and `->queue()` on your export.
