### ISSUE TITLE
Cannot exclude column from ExportBulkAction

### ISSUE THREAD

**Issue by stefanciorici** [pxlrbt/filament-excel#72]
Him

Would be nice to be able to exclude some columns from the ExportBulkAction default list. I know it is possible to create a custom exports but the values in the table and sometimes formatted and changed, so it would only take the information from the database instead of using the values already prepared. 

Is there a way to achieve that?

**Comment by pxlrbt** [comment]
@stefanciorici I just tried this with ExportBulkAction and it works. Can you recreate a reproduction repo?
