### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by kautsar-design** [pxlrbt/filament-excel#84]
$ composer require pxlrbt/filament-excel
Info from https://repo.packagist.org: #StandWithUkraine
./composer.json has been updated
Running composer update pxlrbt/filament-excel
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - pxlrbt/filament-excel[dev-feat/combine-common-configs, dev-fix/docs-chunk-size, dev-fix/fix-tables, dev-refactor/exportables, dev-filament-v3, dev-main, dev-better-query-integration, dev-better-column-attributes-inference, 0.1.0, ..., 0.1.4, v1.0.0-beta, ..., v1.1.11, v2.0.0-alpha] require maatwebsite/excel ^3.1 -> satisfiable by maatwebsite/excel[3.1.0, ..., 3.1.x-dev].
    - maatwebsite/excel[3.1.36, ..., 3.1.x-dev] require phpoffice/phpspreadsheet ^1.18 -> satisfiable by phpoffice/phpspreadsheet[1.18.0, ..., 1.28.0].
    - phpoffice/phpspreadsheet[1.25.0, ..., 1.28.0] require maennchen/zipstream-php ^2.1 -> satisfiable by maennchen/zipstream-php[2.1.0, ..., v2.x-dev].
    - maennchen/zipstream-php[2.1.0, ..., v2.x-dev] require psr/http-message ^1.0 -> found psr/http-message[1.0, 1.0.1, 1.1] but the package is fixed to 2.0 (lock file version) by a partial update and that 
version does not match. Make sure you list it as an argument for the update command.
    - phpoffice/phpspreadsheet[1.18.0, ..., 1.22.0] require psr/simple-cache ^1.0 -> found psr/simple-cache[1.0.0, 1.0.1] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - phpoffice/phpspreadsheet[1.23.0, ..., 1.24.1] require psr/simple-cache ^1.0 || ^2.0 -> found psr/simple-cache[1.0.0, 1.0.1, 2.0.0, 2.x-dev] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - maatwebsite/excel[3.1.0, ..., 3.1.25] require php ^7.0 -> your php version (8.1.17) does not satisfy that requirement.
    - maatwebsite/excel[3.1.26, ..., 3.1.35] require illuminate/support 5.8.*|^6.0|^7.0|^8.0 -> found illuminate/support[v5.8.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - maatwebsite/excel[3.1.41, ..., 3.1.44] require psr/simple-cache ^1.0|^2.0 -> found psr/simple-cache[1.0.0, 1.0.1, 2.0.0, 2.x-dev] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires pxlrbt/filament-excel * -> satisfiable by pxlrbt/filament-excel[dev-feat/combine-common-configs, dev-fix/docs-chunk-size, dev-fix/fix-tables, dev-refactor/exportables, dev-filament-v3, dev-main, dev-better-query-integration, dev-better-column-attributes-inference, 0.1.0, ..., 0.1.4, v1.0.0-beta, ..., v1.1.11, v2.0.0-alpha, 9999999-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require pxlrbt/filament-excel:*" to figure out if any version is installable, or "composer require pxlrbt/filament-excel:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by pxlrbt** [comment]
Closing as stale
