### ISSUE TITLE
Custom Language

### ISSUE THREAD

**Issue by Peagah-Vieira** [pxlrbt/filament-excel#89]
I would like to know if it is possible to configure the language or if you can implement it in the future.
pt_BR
[actions.txt](https://github.com/pxlrbt/filament-excel/files/11928777/actions.txt)
[notifications.txt](https://github.com/pxlrbt/filament-excel/files/11928778/notifications.txt)

**Comment by Peagah-Vieira** [comment]
pt_BR
[actions.txt](https://github.com/pxlrbt/filament-excel/files/11928772/actions.txt)
[notifications.txt](https://github.com/pxlrbt/filament-excel/files/11928773/notifications.txt)

**Comment by Peagah-Vieira** [comment]
pt_BR
[actions.txt](https://github.com/pxlrbt/filament-excel/files/11928775/actions.txt)
[notifications.txt](https://github.com/pxlrbt/filament-excel/files/11928776/notifications.txt)

**Comment by pxlrbt** [comment]
If you do a PR, I can merge them. Do you know how it works?

**Comment by Peagah-Vieira** [comment]
It's done, Thanks for the package!

**Comment by pxlrbt** [comment]
Thanks for the PR.
