### ISSUE TITLE
ExportBulkAction::withFilename does not exist

### ISSUE THREAD

**Issue by sergeynilov** [pxlrbt/filament-excel#91]
In laravel 9 app with  filament 2.17.49 and pxlrbt/filament-excel 1.1.11 I use ExportBulkAction
and it works ok for me, but when I try to use askForFilename or withFilename methods :

```
    use pxlrbt\FilamentExcel\Actions\Tables\ExportBulkAction;
            ...

            ->bulkActions([
                Tables\Actions\DeleteBulkAction::make(),
                ExportBulkAction::make()
//                    ->askForFilename()
                    ->withFilename(fn ($filename) => 'prefix-' . $filename),
            ])
```

I got error : 
`Method pxlrbt\FilamentExcel\Actions\Tables\ExportBulkAction::withFilename does not exist.
`
What is wrong in my code and how this issue can be salved ?

**Comment by pxlrbt** [comment]
Please read the docs carefully. The method belongs to the Export not the ExportAction.
