### ISSUE TITLE
Manage Queue

### ISSUE THREAD

**Issue by roomdada** [pxlrbt/filament-excel#92]
How to manage the queue to avoid failures, and my second concern is how to customize it to send file attachments via email?

![Screenshot 2023-07-03 111615](https://github.com/pxlrbt/filament-excel/assets/61591337/b377b6fd-aa9b-4745-ae38-0357c04c5914)

**Comment by pxlrbt** [comment]
> How to manage the queue to avoid failures

Please check the Laravel log on what goes wrong and report back if it's an issue related to this package. 

> how to customize it to send file attachments via email?

That's not really a supported method. Would be a nice feature request, but currently I don't have the time to add new feature.

You could try to queue a chained job and get the excel filename from the first job.
