### ISSUE TITLE
Queued export not working!

### ISSUE THREAD

**Issue by MuriloSo** [pxlrbt/filament-excel#96]
For some reason queued exports do not have the file written to storage. The worker processes the jobs, but at the end the file is not saved.
The "storage/app/filament-excel" folder is always empty, even after the job is processed.

**Comment by MuriloSo** [comment]
> Weird. Never had that issue. The jobs don't fail? No error logs?

Jobs don't fail and no error logs...
<img width="1847" alt="image" src="https://github.com/pxlrbt/filament-excel/assets/14274845/2055f584-f3ce-42b5-8098-6a7994984474">

And the filament-excel directory is still empty.
<img width="344" alt="image" src="https://github.com/pxlrbt/filament-excel/assets/14274845/a801654d-fb55-4c73-8e36-c41d5f3ebd13">

**Comment by pxlrbt** [comment]
Hard to tell. The file generation is not handle by this plugin. Maybe try debugging the `StoreQueuedExport` job

**Comment by williamengbjerg** [comment]
@MuriloSo Did you find a solution?  I had similar issue and discovered that FilamentExcelServiceProvider blocks the notification download. Im using it in a custom page, with a docker setup. Not sure if that has a specific reason to not download or show, @pxlrbt ? 

Set up an event to change this that prevented the download to show. 
`
if (! Storage::exists('filament-excel/'.$export['filename'])) {
    continue;
}`

to this: 

`if (! Storage::disk('filament-excel')->exists($export['filename'])) {
    continue;
}`

**Comment by pxlrbt** [comment]
@williamengbjerg Those two lines should be identical unless you change the folder. So the last one is better indeed. What did this fix for you? It's showing notifications now, where it wasn't showing notifications before?

**Comment by williamengbjerg** [comment]
@pxlrbt Yes, it resolved the problem by displaying the notification and the download file/button afterward.

**Comment by pxlrbt** [comment]
@williamengbjerg v2.1.4 should fix this then.

**Comment by pxlrbt** [comment]
@MuriloSo Could you debug this and get more information?

**Comment by williamengbjerg** [comment]
@pxlrbt Works! Guess I can remove my event listener 🤗 Thanks a lot.
